### ISSUE TITLE
404 on TDD Anti-Patterns by James Carr.

### ISSUE THREAD

**Issue by magoyette** [magoyette/software-development-readings#1]
Need to check if the link will be fixed later.
https://blog.james-carr.org/2006/11/03/tdd-anti-patterns/

**Comment by magoyette** [comment]
This issue will be closed. The blog post has been erased because of hosting issues: https://blog.james-carr.org/the-reboot-289b74908905#.c718pays5

**Comment by githubaff0** [comment]
https://web.archive.org/web/20160605001457/http://blog.james-carr.org:80/2006/11/03/tdd-anti-patterns/
